if(UNIX AND NOT APPLE)
  set(XTALOPT_OS_BUILD "linux")
elseif(APPLE)
  set(XTALOPT_OS_BUILD "macos")
elseif(WIN32)
  set(XTALOPT_OS_BUILD "windows")
else()
  set(XTALOPT_OS_BUILD "unknownOS")
endif()

string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" ARCH)
if(ARCH MATCHES "arm64|aarch64")
  set(XTALOPT_PROCC_BUILD "arm64")
elseif(ARCH MATCHES "armv7l|armv6l")
  set(XTALOPT_PROCC_BUILD "arm32")
elseif(ARCH MATCHES "x86_64|amd64")
  set(XTALOPT_PROCC_BUILD "x86_64")
elseif(ARCH MATCHES "i386|i686|x86")
  set(XTALOPT_PROCC_BUILD "x86_32")
else()
  set(XTALOPT_PROCC_BUILD "unknown")
endif()

if(BUILD_XTALOPT_GUI)
  set(XTALOPT_INTERFACE_BUILD "gui")
else()
  set(XTALOPT_INTERFACE_BUILD "cli")
endif()

if(ENABLE_LIBSSH)
  set(XTALOPT_SSH_BUILD "-libssh")
else()
  set(XTALOPT_SSH_BUILD "") # System SSH is included by default.
endif()

set(CPACK_PACKAGE_FILE_NAME
    "XtalOpt-${XtalOpt_VERSION_FULL}-${XTALOPT_OS_BUILD}-${XTALOPT_PROCC_BUILD}-${XTALOPT_INTERFACE_BUILD}${XTALOPT_SSH_BUILD}")
set(CPACK_PACKAGE_VERSION_MAJOR ${XtalOpt_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${XtalOpt_VERSION_MINOR})
# Some package generators require a numeric patch field. Keep the full version in the file name.
string(REGEX MATCH "^[0-9]+" _xtalopt_cpack_patch "${XtalOpt_VERSION_PATCH}")
set(CPACK_PACKAGE_VERSION_PATCH ${_xtalopt_cpack_patch})
set(CPACK_PACKAGE_INSTALL_DIRECTORY "XtalOpt")
set(CPACK_PACKAGE_VENDOR "Zurek Lab")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")
set(CPACK_CREATE_DESKTOP_LINKS "xtalopt")
set(CPACK_PACKAGE_EXECUTABLES "xtalopt" "XtalOpt")
set(CPACK_MONOLITHIC_INSTALL ON)

if(NOT CPACK_GENERATOR)
  if(APPLE)
    set(CPACK_GENERATOR "ZIP")
  elseif(WIN32)
    set(CPACK_GENERATOR "NSIS")
  else()
    set(CPACK_GENERATOR "TGZ")
  endif()
endif()

if(NOT DEFINED CPACK_SOURCE_GENERATOR)
  set(CPACK_SOURCE_GENERATOR "TGZ")
endif()

# NSIS stuff
set(CPACK_NSIS_HELP_LINK "https://xtalopt.github.io")
set(CPACK_NSIS_URL_INFO_ABOUT "https://xtalopt.github.io")
set(CPACK_NSIS_INSTALLED_ICON_NAME "bin\\\\xtalopt.exe")
set(CPACK_NSIS_MUI_ICON "${CMAKE_SOURCE_DIR}/src/xtalopt/images\\\\xtalopt-logo.ico")
# Set package logos for macOS and Linux.
if(APPLE)
  set(CPACK_PACKAGE_ICON  "${CMAKE_SOURCE_DIR}/src/xtalopt/images/xtalopt-logo.icns")
elseif(NOT WIN32)
  set(CPACK_PACKAGE_ICON  "${CMAKE_SOURCE_DIR}/src/xtalopt/images/xtalopt-logo.png")
endif()
set(CPACK_NSIS_MODIFY_PATH ON)

include(CPack)
